bqcup singgle site added
bqckup/bqckup pull request #51
Opened 2024-08-10 03:18 UTC by ahmadridhoramadhan

added
# singgle site command added

2024-08-10 04:40 UTC, thisnugroho requested changes

2024-08-10 04:40 UTC, thisnugroho commented on constant/__init__.py
>  from os import path
Tidak perlu di commit ini

2024-08-10 04:40 UTC, thisnugroho commented on classes/bqckup.py
> +                    continue
Coba cek lagi bagian ini,kalo config domain nya ada banyak

2024-08-10 06:03 UTC, ahmadridhoramadhan commented on classes/bqckup.py
> +                    continue
sudah ka

2024-08-11 15:12 UTC, thisnugroho approved these changes

2024-08-11 15:12 UTC, merged