Report
bqckup/bqckup pull request #68
Opened 2024-08-21 06:55 UTC by ahmadridhoramadhan

## added
- add split_list() to helpers
- add command report ``bqckup report`` 
![image](https://github.com/user-attachments/assets/affce466-7148-4e77-89f9-a10877240e9b)

2024-08-21 14:17 UTC, thisnugroho approved these changes

2024-08-21 14:21 UTC, thisnugroho commented
Sudah OK 😄 , sisa yang memindah report ke `run()` lagi lah @ahmadridhoramadhan

2024-08-22 01:03 UTC, thisnugroho requested changes
Sedikit lagi, ada beberapa perubahan yang harus di sesuaikan 👍

2024-08-22 01:03 UTC, thisnugroho commented on classes/bqckup.py
> +
Tidak perlu, sudah ada disini: https://github.com/bqckup/bqckup/blob/c5867a3f9792d02e25f5993efcdb3cbe89dd3ac3/app.py#L223-L226

2024-08-22 01:03 UTC, thisnugroho commented on bqckup.py
>  @ bq_cli.command()
Di comment aja, biar gak masuk ke `--help.`

2024-08-22 01:03 UTC, thisnugroho commented on classes/report.py
> +                        interval = Bqckup()._interval_in_number(site['options']['interval'])
Sepertinya kurang tepat kalo kita taruh `_interval_in_number` di class bqckup, pindahkan saja ke helper datetime, soalnya kada ada hubungan langsung dengan class Bqckup, hanya sebagai converter aja itu.

2024-08-22 01:03 UTC, thisnugroho commented on classes/report.py
> +                        contents_from_two_month_ago = list(filter(filter_two_month_ago_and_by_same_site, backups.get('Contents')))
Apa maksudnya `Two Month` ini

2024-08-22 01:03 UTC, thisnugroho commented on classes/report.py
> +                        contents_files = list(filter(lambda x: x.get('Key').split('.')[-2] != 'sql', contents_from_two_month_ago))
Ini harusnya bisa lebih di rapikan lagi, banyak code redundant.

```python
contents_database = True if condition else False
contents_files = not contents_database
```

misal seperti itu

2024-08-22 01:03 UTC, thisnugroho commented on classes/report.py
> +        return reason['error']
method ini masih sulit di pahami, apakah bisa dibuat jadi lebih mudah di pahami, misalnya di bagian ini

```python
# Ini maksudnya apa, dan ngapain
if i + i < len(contents)
```

2024-08-22 01:24 UTC, ahmadridhoramadhan commented on classes/report.py
> +                        contents_from_two_month_ago = list(filter(filter_two_month_ago_and_by_same_site, backups.get('Contents')))
itu buat periksa yang interval nya monthly kalo 1 bulan aja jadwalnya kalo ngga dapat

2024-08-22 06:20 UTC, thisnugroho approved these changes
oksip

2024-08-22 06:21 UTC, merged